# Base Python Image
FROM python:3.10-slim

# Working Directory in the Container
WORKDIR /webscraper

# Python settings to prevent python from writing .pyc files and buffer output
# (i.e see print statments as they are executed, instead of waiting for a buffer)
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Copying requirements.txt to install the required packages
COPY requirements.txt .

# RUN Command to install the packages
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .